### ISSUE TITLE
Power storage strategy

### ISSUE THREAD

**Issue by fusedFET** [fusedFET/ShinaiSense#1]
# Power supply
## Associated requirements
- The system shall operate at least 3h continuously.
- The system shall operate from a battery.
- The system shall operate at 2.5v.
- The power storage/conversion system shall not exceed 50g.
- The power storage/conversion system shall support realistic mechanical forces caused by the impacts.
## Tasks
- [ ] Select a Li-Ion battery @vanderpipou 
- [ ] Evaluate necessity of ULVO & CC systems. @fusedFET 
- [ ] Implement on schematics. @fusedFET.
